### ISSUE TITLE
Misplaced postman-collection dependency breaks Yarn PNP

### ISSUE THREAD

**Issue by TravisBernard** [postmanlabs/postman-sandbox#848]
`postman-collection` has been entered as a devDependency however it is used directly in the code.  This breaks Yarn PNP with the [<name> is trying to require <name> without it being listed in its dependencies](https://classic.yarnpkg.com/lang/en/docs/pnp/troubleshooting/#toc-is-trying-to-require-without-it-being-listed-in-its-dependencies) error.

Moving postman-collection from devDependencies to dependencies seems to resolve the issue.  I have a fix prepared, I will reference this issue in the PR.

**Comment by codenirvana** [comment]
@TravisBernard thanks for reporting this.

Published a new version `postman-sandbox@4.1.2` with your fix.

**Comment by TravisBernard** [comment]
Awesome.  Thanks for the quick turnaround @codenirvana
