### ISSUE TITLE
Hi! script to change the initial value and current value?

### ISSUE THREAD

**Issue by BroJenuel** [postmanlabs/postman-sandbox#850]
I'm trying to run this script but it seems like it's only changing the initial value, and the token variable cant be used on another request, I have to edit it manually copying it to the current value.

![image](https://user-images.githubusercontent.com/31676163/183417591-479738de-5d0d-4737-8369-b1276b98a4e0.png)

**Comment by codenirvana** [comment]
@BroJenuel please report this issue here: https://github.com/postmanlabs/postman-app-support/issues.
